{% set name = "haesleinhuepf-pyqode.core" %}
{% set version = "2.15.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/haesleinhuepf-pyqode.core-{{ version }}.tar.gz
  sha256: 3b8ca2623244cccc5d7cf3ab02906375a597686d670bab772049e18177db16eb

build:
  entry_points:
    - pyqode-console = pyqode.core.tools.console:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pyqt_distutils
    - pytest
    - python {{ python_min }}
  run:
    - future
    - pygments
    - python >={{ python_min }}
  run_constrained:
    - pyqode.core =99999999999999

test:
  imports:
    - pyqode
  commands:
    - pip list
    - pip check
    # - pyqode-console --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/pyqode.core
  summary: Fork of PyQode, the PyQt/PySide Source Code Editor Widget, maintained by haesleinhuepf
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
